os:
- linux
language: python
deploy:
  provider: gae
  project: lpBackend
before_install:
- openssl aes-256-cbc -K $encrypted_52559f98c00a_key -iv $encrypted_52559f98c00a_iv
  -in client-secret.json.enc -out client-secret.json -d
