os:
- linux
language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- git clone https://github.com/thtrieu/darkflow
- cd darkflow
- python setup.py build_ext --inplace
- pip install .
- cd ../
- sudo apt-get install libsm6 libxrender1 libfontconfig1c
- python app.py
deploy:
  provider: gae
  keyfile: YOUR SERVICE ACCOUNT JSON FILE
  project: YOUR PROJECT ID
before_install:
- openssl aes-256-cbc -K $encrypted_a3d285ac981a_key -iv $encrypted_a3d285ac981a_iv
  -in gcp.json.enc -out gcp.json -d
