os:
  - linux
language: python
python:
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - git clone https://github.com/thtrieu/darkflow
  - cd darkflow
  - python setup.py build_ext --inplace
  - pip install .
  - cd ../
  - python app.py

deploy:
  provider: gae
  keyfile: "YOUR SERVICE ACCOUNT JSON FILE"
  project: "YOUR PROJECT ID"